jobs:
- job: windows_latest
  pool:
    vmimage: windows-latest
  steps:
  - script: dotnet tool install --global FlubuCore.Tool --version 5.1.8
    displayName: Install flubu
  - script: flubu buildVersion --nd
    displayName: buildVersion
  - script: flubu compile --nd
    displayName: compile
  - script: flubu test --nd
    displayName: test
- job: ubuntu_latest
  pool:
    vmimage: ubuntu-latest
  steps:
  - script: dotnet tool install --global FlubuCore.Tool --version 5.1.8
    displayName: Install flubu
  - script: flubu buildVersion --nd
    displayName: buildVersion
  - script: flubu compile --nd
    displayName: compile
  - script: flubu test --nd
    displayName: test
- job: macOs_latest
  pool:
    vmimage: macOs-latest
  steps:
  - script: dotnet tool install --global FlubuCore.Tool --version 5.1.8
    displayName: Install flubu
  - script: flubu buildVersion --nd
    displayName: buildVersion
  - script: flubu compile --nd
    displayName: compile
  - script: flubu test --nd
    displayName: test
