jobs:
- job: windows_latest
  pool:
    vmimage: windows-latest
  steps:
  - task: DotNetCoreInstaller@1
    displayName: Install .net core sdk
    inputs:
      version: 3.1.100
  - script: dotnet tool install --global FlubuCore.Tool --version 5.1.8
    displayName: Install flubu
  - script: flubu buildVersion --nd
    displayName: buildVersion
    workingDirectory: src
  - script: flubu compile --nd
    displayName: compile
    workingDirectory: src
  - script: flubu test --nd
    displayName: test
    workingDirectory: src
- job: ubuntu_latest
  pool:
    vmimage: ubuntu-latest
  steps:
  - task: DotNetCoreInstaller@1
    displayName: Install .net core sdk
    inputs:
      version: 3.1.100
  - script: dotnet tool install --global FlubuCore.Tool --version 5.1.8
    displayName: Install flubu
  - script: flubu buildVersion --nd
    displayName: buildVersion
    workingDirectory: src
  - script: flubu compile --nd
    displayName: compile
    workingDirectory: src
  - script: flubu test --nd
    displayName: test
    workingDirectory: src
- job: macOs_latest
  pool:
    vmimage: macOs-latest
  steps:
  - task: DotNetCoreInstaller@1
    displayName: Install .net core sdk
    inputs:
      version: 3.1.100
  - script: dotnet tool install --global FlubuCore.Tool --version 5.1.8
    displayName: Install flubu
  - script: flubu buildVersion --nd
    displayName: buildVersion
    workingDirectory: src
  - script: flubu compile --nd
    displayName: compile
    workingDirectory: src
  - script: flubu test --nd
    displayName: test
    workingDirectory: src
