name: build
on:  [push, pull_request] 
jobs:
  windows-latest:
    name: windows-latest
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Flubu
      run: dotnet tool install --global FlubuCore.Tool --version 5.1.8
    - name: buildVersion
      working-directory: src
      run: flubu buildVersion --nd
    - name: compile
      working-directory: src
      run: flubu compile --nd
    - name: test
      working-directory: src
      run: flubu test --nd
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Flubu
      run: dotnet tool install --global FlubuCore.Tool --version 5.1.8
    - name: buildVersion
      working-directory: src
      run: flubu buildVersion --nd
    - name: compile
      working-directory: src
      run: flubu compile --nd
    - name: test
      working-directory: src
      run: flubu test --nd
  macos-latest:
    name: macos-latest
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Flubu
      run: dotnet tool install --global FlubuCore.Tool --version 5.1.8
    - name: buildVersion
      working-directory: src
      run: flubu buildVersion --nd
    - name: compile
      working-directory: src
      run: flubu compile --nd
    - name: test
      working-directory: src
      run: flubu test --nd
